# Generated by Django 3.1.3 on 2020-11-13 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbOferta',
            fields=[
                ('oferta_id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_oferta', models.DateField()),
                ('titulo_oferta', models.CharField(max_length=100)),
                ('rua_oferta', models.CharField(max_length=100)),
                ('numero_endereco_oferta', models.CharField(max_length=10)),
                ('bairro_oferta', models.CharField(max_length=100)),
                ('cidade_oferta', models.CharField(max_length=100)),
                ('pessoas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferta', to='pessoas.tbpessoa')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
    ]
