# Generated by Django 3.1.3 on 2020-11-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servico', '0001_initial'),
        ('demanda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbdemanda',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='servico.tbservico'),
        ),
    ]
