# Generated by Django 3.1.3 on 2020-11-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demanda', '0004_tbdemanda_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbdemanda',
            name='demanda',
            field=models.ManyToManyField(related_name='demandas', to='demanda.TbDemanda'),
        ),
    ]
