# Generated by Django 3.1.3 on 2020-11-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0004_auto_20201117_0930'),
        ('demanda', '0005_tbdemanda_demanda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbdemanda',
            name='demanda',
        ),
        migrations.AddField(
            model_name='tbdemanda',
            name='servico',
            field=models.ManyToManyField(related_name='demanda', to='servico.TbServico'),
        ),
    ]
