# Generated by Django 3.1.3 on 2020-11-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcampanha',
            name='bairro_campanha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbcampanha',
            name='cidade_campanha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbcampanha',
            name='numero_endereco_campanha',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbcampanha',
            name='rua_campanha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
