# Generated by Django 3.1.3 on 2020-11-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbcampanha',
            old_name='id_campanha',
            new_name='campanha_id',
        ),
    ]
