# Generated by Django 3.1.3 on 2020-11-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_auto_20201111_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcampanha',
            name='bairro_campanha',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbcampanha',
            name='numero_endereco_campanha',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbcampanha',
            name='rua_campanha',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
