# Generated by Django 3.1.3 on 2020-11-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0003_auto_20201111_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcampanha',
            name='cidade_campanha',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
