# Generated by Django 3.1.3 on 2020-11-13 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0003_auto_20201113_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbVoluntariado',
            fields=[
                ('voluntariado_id', models.AutoField(primary_key=True, serialize=False)),
                ('desc_voluntariado', models.TextField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntariado', to='pessoas.tbpessoa')),
            ],
        ),
    ]
