# Generated by Django 3.1.3 on 2020-11-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbvoluntariado',
            options={'verbose_name': 'Voluntariado', 'verbose_name_plural': 'Voluntariados'},
        ),
        migrations.AddField(
            model_name='tbvoluntariado',
            name='titulo_voluntariado',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
