# Generated by Django 3.1.3 on 2021-01-15 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fone',
            fields=[
                ('fone_id', models.AutoField(primary_key=True, serialize=False)),
                ('nr_fone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
            options={
                'verbose_name': 'Fone',
                'verbose_name_plural': 'Fones',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('pessoa_id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf_pessoa', models.CharField(max_length=11, unique=True)),
                ('nome_pessoa', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('nasc_pessoa', models.DateField()),
                ('email_pessoa', models.EmailField(max_length=254)),
                ('fone', models.ManyToManyField(related_name='pessoas', to='pessoas.Fone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
    ]
