# Generated by Django 3.1.3 on 2020-11-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbPessoa',
            fields=[
                ('pessoa_id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf_pessoa', models.CharField(max_length=11, unique=True)),
                ('nome_pessoa', models.CharField(max_length=200)),
                ('nasc_pessoa', models.DateField()),
                ('email_pessoa', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
    ]
