# Generated by Django 3.1.3 on 2021-01-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='password',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='username',
            field=models.CharField(default=' ', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
