# Generated by Django 3.1.3 on 2020-11-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_remove_tbfone_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbpessoa',
            name='fone',
        ),
        migrations.AddField(
            model_name='tbpessoa',
            name='fone',
            field=models.ManyToManyField(related_name='pessoas', to='pessoas.TbFone'),
        ),
    ]
