# Generated by Django 3.1.3 on 2020-11-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oferta', '0001_initial'),
        ('voluntariado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbServico',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_servico', models.CharField(max_length=100)),
                ('desc_servico', models.TextField(max_length=1400)),
                ('oferta', models.ManyToManyField(related_name='servicos', to='oferta.TbOferta')),
                ('voluntariado', models.ManyToManyField(related_name='voluntariados', to='voluntariado.TbVoluntariado')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
