# Generated by Django 3.1.3 on 2020-11-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbServico',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_servico', models.CharField(max_length=100)),
                ('desc_servico', models.TextField(max_length=1400)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
