# Generated by Django 3.1.3 on 2020-11-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demanda', '0001_initial'),
        ('voluntariado', '0001_initial'),
        ('oferta', '0001_initial'),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbservico',
            name='demanda',
            field=models.ManyToManyField(related_name='demandas', to='demanda.TbDemanda'),
        ),
        migrations.AddField(
            model_name='tbservico',
            name='oferta',
            field=models.ManyToManyField(related_name='servicos', to='oferta.TbOferta'),
        ),
        migrations.AddField(
            model_name='tbservico',
            name='voluntariado',
            field=models.ManyToManyField(related_name='voluntariados', to='voluntariado.TbVoluntariado'),
        ),
    ]
