# Generated by Django 3.1.3 on 2020-11-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbservico',
            name='demanda',
        ),
    ]
