# Generated by Django 3.1.3 on 2020-11-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_remove_tbservico_demanda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbservico',
            name='oferta',
        ),
        migrations.RemoveField(
            model_name='tbservico',
            name='voluntariado',
        ),
    ]
